config/routes.rb
Mh::Application.routes.draw do

  resources :movement_indicators, only: [:index, :create] do
    collection do
      get :details
      get :error
    end
  end

  resources :movement_indicator_suggestions do
    collection do
      get :fetch_suggestions
      get :fetch_declined_suggestions
      get :confirm
      post :post_to_infobase
    end
  end


  get "dashboard/index"

  resources :imports, :only => [:show, :new, :create, :update, :destroy, :edit] do
    collection do
      get :download_sample_contacts_csv
      post :create_survey_question
      post :import
    end
  end

  # Interactions
  match 'profile/:id' => 'interactions#show_profile', as: "profile"
  resources :interactions do
    collection do
      get :change_followup_status
      get :reset_edit_form
      get :show_edit_interaction_form
      get :show_new_interaction_form
      get :search_initiators
      get :search_receivers
      get :load_more_interactions
      get :load_more_all_feeds
      get :create_label
      get :set_labels
      get :set_permissions
      get :set_groups
      get :search_leaders
    end
  end

  match 'imports/:id/labels' => 'imports#labels'
  match 'show_assign_search' => 'contacts#show_assign_search'
  match 'show_hidden_questions' => 'contacts#show_hidden_questions'
  match 'show_search_hidden_questions' => 'contacts#show_search_hidden_questions'
  match 'display_sidebar' => 'contacts#display_sidebar'
  match 'display_new_sidebar' => 'contacts#display_new_sidebar'
  match 'show_other_orgs' => 'surveys#show_other_orgs'
  match 'copy_survey' => 'surveys#copy_survey'
  match 'sent_messages' => 'messages#sent_messages'
  match 'search_locate_contact' => 'contacts#search_locate_contact'

  resources :group_labels, :only => [:create, :destroy]

  ActiveAdmin.routes(self)
  ActiveAdmin::ResourceController.class_eval do
    def authenticate_admin!
      unless user_signed_in? && SuperAdmin.find_by_user_id_and_site(current_user.id, 'MissionHub')
        render :file => Rails.root.join(mhub? ? 'public/404_mhub.html' : 'public/404.html'), :layout => false, :status => 404
        false
      end
    end
  end

  resources :groups do
    resources :group_labelings, :only => [:create, :destroy]
    resources :group_memberships, :only => [:create, :destroy] do
      collection do
        get :search
      end
    end
  end

  resources :survey_responses do
    collection do
      get :thanks
      get :facebook
      get :live
    end
  end

  resources :leaders, :only => [:new, :create, :update, :destroy] do
    collection do
      get :search
      put :add_person
    end
  end

  resources :organizational_permissions, :only => :update do
    collection do
      post :move_to
      post :update_all
    end
    member do
      get :set_current
      get :set_primary
    end
  end

  resources :organizational_labels do
    collection do
      post :update_all
    end
  end

  # resources :rejoicables

  resources :saved_contact_searches#, :only => [:show, :create, :edit, :destroy, :index]
  match "/saved_contact_searches/:id" => "saved_contact_searches#update"

  resources :followup_comments, :only => [:index, :create, :destroy]

  resources :contact_assignments, :only => [:create]

  resources :ministries

  resources :sms_keywords, :only => [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      post :accept_twilio
    end
  end

  match "/people" => "contacts#all_contacts"
  match "/allcontacts?assigned_to=unassigned" => "contacts#all_contacts", as: "unassigned_contacts"
  get "/contacts" => redirect("/allcontacts")
  match "/old_directory" => "people#index"
  resources :people, :only => [:show, :create, :edit, :update, :destroy] do
    collection do
      get :export
      get :merge
      post :confirm_merge
      post :do_merge
      get :hide_update_notice
      get :search_ids
      post :bulk_email
      post :bulk_sms
      post :bulk_comment
      get :all
      post :update_permissions
      post :update_permission_status
      post :bulk_delete
      post :bulk_archive
      get :facebook_search
      get :index
    end
    member do
      get :merge_preview
      get :involvement
    end
  end

  resources :labels, :only => [:create, :update, :destroy, :index, :new, :edit] do
    collection do
      post :create_now
      post :add_label
      post :edit_label
    end
  end

  namespace :admin do
    resources :email_templates

  end

  # namespace :admin do
  #   resources :organizations
  # end

  resources :organizations, :only => [:show, :new, :create, :edit, :update, :destroy, :index] do
    collection do
      get :search
      get :thanks
      post :signup
      get :settings
      post :update_settings
      get :cleanup
      get :transfer
      get :available_for_transfer
      get :queue_transfer
      post :do_transfer
      post :archive_contacts
      post :archive_leaders
      post :create_from_crs
      get :api
      get :generate_api_secret
      get :show_hidden_questions
      get :display_sidebar
    end
    member do
      get :update_from_crs
    end
  end

  resources :charts do
    collection do
      get :snapshot
      post :update_snapshot_movements
      post :update_snapshot_range
      get :goal
      get :trend
    end
  end

  resources :surveys, :only => [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get :start
    end
    collection do
      get :index_admin
      get :stop
    end
    resources :questions, controller: "surveys/questions" do
      member do
        put :hide
        put :unhide
      end
      collection do
        post :reorder
      end
    end
  end

  match "/dashboard" => "dashboard#index"
  get "welcome/index"
  get "welcome/duplicate"
  match 'tutorials' => "welcome#tutorials"
  get "/test" => "welcome#test"

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    match "/sign_in", to: "sessions#new"
    match "/sign_out", to: "sessions#destroy"
    match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'
    match '/users/auth/facebook_mhub/callback', to: 'users/omniauth_callbacks#facebook_mhub'
  end
  match '/auth/facebook/logout' => 'application#facebook_logout', as: :facebook_logout

  match "/application.manifest" => OFFLINE

  post "sms/mo"
  get "sms/mo"

  match "/allcontacts" => "contacts#all_contacts", as: "all_contacts"
  match "/mycontacts" => "contacts#my_contacts", as: "my_contacts"
  match "/my_contacts_all" => "contacts#my_contacts_all", as: "my_contacts_all"
  resources :contacts, :only => [:show, :create, :edit, :update, :destroy, :index] do
    collection do
      get :all_contacts
      get :my_contacts
      get :mine
      get :mine_all
      get :contacts_all
      post :send_reminder
      put :create_from_survey
      delete :destroy
      post :bulk_destroy
      post :send_vcard
      get :send_bulk_vcard
      get :import_contacts
      post :csv_import
      get :download_sample_contacts_csv
      get :search_by_name_and_email
      get :auto_suggest_send_email
      get :auto_suggest_send_text
    end
  end

  resources :vcards, :only => [:create] do
    collection do
      get :bulk_create
    end
  end

  namespace :api do
    scope '(/:version)', version: /v\d+?/ do  #module: :api
      resources :people do
        collection do
          get :leaders
        end
      end
      resources :friends
      get 'contacts/search' => 'contacts#search'
      resources :contacts do
        resource :photo
      end
      get "contact_assignments/list_leaders" => "contact_assignments#list_leaders"
      get "contact_assignments/list_organizations" => "contact_assignments#list_organizations"
      resources :contact_assignments
      resources :followup_comments
      resources :interactions
      resources :roles
      resources :permissions
      resources :organizational_labels
      resources :organizational_permissions
      resources :organizations
    end
  end

  namespace :apis do

    api_version(module: 'V3', header: {name: 'API-VERSION', value: 'v3'}, parameter: {name: "version", value: 'v3'}, path: {value: 'v3'}) do
      resources :contact_assignments do
        collection do
          put :bulk_update
          delete :bulk_destroy
        end
      end
      resources :people do
        collection do
          get :ids
          delete :bulk_destroy
        end
      end
      resources :organizations
      resources :answers
      resources :surveys do
        resources :questions
      end
      resources :questions
      resources :followup_comments
      resources :roles
      resources :organizational_roles
      resources :interactions
      resources :interaction_types
      resources :labels
      resources :permissions
      resources :organizational_labels do
        collection do
          post :bulk
          post :bulk_create
          delete :bulk_destroy
        end
      end
      resources :organizational_permissions do
        collection do
          post :bulk
          post :bulk_create
          post :bulk_archive
          delete :bulk_destroy
        end
      end
    end
  end

  root to: "welcome#index"
#  match 'home' => 'welcome#home', as: 'user_root' ---- LOOK FOR THIS IN application_controller.rb
  match 'wizard' => 'welcome#wizard', as: 'wizard'
  match 'terms' => 'welcome#terms', as: 'terms'
  match 'privacy' => 'welcome#privacy', as: 'privacy'

  # SMS keyword state transitions
  match '/admin/sms_keywords/:id/t/:transition' => 'admin/sms_keywords#transition', as: 'sms_keyword_transition'
  match '/admin/sms_keywords/approve'

  match '/admin/organizations/:id/t/:transition' => 'admin/organizations#transition', as: 'organization_transition'
  match '/admin/organizations/approve'

  # Map keyword responses with phone numbers
  match 'c/:keyword(/:received_sms_id)' => 'survey_responses#new', as: 'contact_form'
  match 'm/:received_sms_id' => 'survey_responses#new'

app/controllers/apis/v3/labels_controller.rb
class Apis::V3::LabelsController < Apis::V3::BaseController
  before_filter :get_label, only: [:show, :update, :destroy]

  def index
    order = params[:order] || 'name'

    list = add_includes_and_order(labels, order: order)

    render json: list,
           callback: params[:callback],
           scope: {include: includes, organization: current_organization, since: params[:since]}
  end

  def show
    render json: @label,
           callback: params[:callback],
           scope: {include: includes, organization: current_organization}
  end

  def create
    label = Label.new(params[:label])
    label.organization_id = current_organization.id

    if label.save
      render json: label,
             status: :created,
             callback: params[:callback],
             scope: {include: includes, organization: current_organization}
    else
      render json: {errors: label.errors.full_messages},
             status: :unprocessable_entity,
             callback: params[:callback]
    end
  end

  def update
    if @label.organization_id == 0
      render json: {errors: ["You can't update the default labels"]},
             status: :unprocessable_entity,
             callback: params[:callback]
    else
      if @label.update_attributes(params[:label])
        render json: @label,
               callback: params[:callback],
               scope: {include: includes, organization: current_organization}
      else
        render json: {errors: @label.errors.full_messages},
               status: :unprocessable_entity,
               callback: params[:callback]
      end
    end
  end

  def destroy
    if @label.organization_id == 0
      render json: {errors: ["You can't delete the default labels"]},
             status: :unprocessable_entity,
             callback: params[:callback]
    else
      @label.destroy
      render json: @label,
             callback: params[:callback],
             scope: {include: includes, organization: current_organization}
    end
  end

  private

  def labels
    current_organization.labels
  end

  def get_label
    @label = add_includes_and_order(labels).find(params[:id])

  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_filter :ensure_current_org
  before_filter :authorize
  before_filter :set_label, :only => [:new, :edit, :update, :destroy]

  def index
    @organizational_labels = current_organization.non_default_labels
    @system_labels = current_organization.default_labels
  end

  def new
  end

  def edit
  end

  def add_label
    @name = params[:name]
    @message = t('manage_labels.name_is_required')
    if @name.present?
      if Label.where("organization_id IN (?) AND LOWER(name) = ?", [current_organization.id,0], @name.downcase).present?
        @message = t('manage_labels.label_exists')
      else
        @new_label = Label.create(organization_id: current_organization.id, name: @name)
        if @new_label.present?
          @message = t('manage_labels.add_label_success')
        else
          @message = t('manage_labels.add_label_failed')
        end
      end
    end
  end

  def edit_label
    @name = params[:name]
    @id = params[:id]
    @message = t('manage_labels.name_is_required')
    @status = false
    if @name.present? && @id.present?
      @message = t('manage_labels.add_label_failed')
      if @update_label = Label.find_by_id_and_organization_id(@id, current_organization.id)
        if Label.where("organization_id IN (?) AND LOWER(name) = ?", [current_organization.id,0], @name.downcase).present?
          @message = t('manage_labels.label_exists')
        else
          @update_label.name = @name
          @update_label.save
          @message = t('manage_labels.edit_label_success')
          @status = true
        end
      end
    end
  end

  def create
    Label.transaction do
      @label = Label.new(params[:label])
      @label.organization_id = current_organization.id
      if @label.save
        redirect_to labels_path
      else
        render :new
      end
    end
  end

  def create_now
    @status = false
    if params[:name].present?
      if Label.where("LOWER(name) = ? AND organization_id IN (?)", params[:name].downcase, [current_organization.id,0]).present?
        @msg_alert = t('contacts.index.add_label_exists')
      else
        @new_label = Label.create!(name: params[:name], organization_id: current_organization.id) if params[:name].present?
        if @new_label.present?
          @status = true
          @msg_alert = t('contacts.index.add_label_success')
        else
          @msg_alert = t('contacts.index.add_label_failed')
        end
      end
    else
      @msg_alert = t('contacts.index.add_label_empty')
    end
  end

  def update
    if @label.update_attributes(params[:label])
      redirect_to labels_path
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path
  end

 protected
  def authorize
    authorize! :manage_labels, current_organization
  end

  def set_label
    @label = case action_name
    when 'new' then Label.new
    else Label.find(params[:id])
    end
  end
end

app/views/labels/_form.html.erb
<% if @label.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<table border="0" cellspacing="0" cellpadding="0" class="modal_person_info">
  <tr>
    <td class="left"><%= t('labels.name') %>:</td>
    <td><%= f.text_field :name %></td>
  </tr>
</table>

<div class="actions">
  <%= f.submit button_label %>
</div>

app/views/labels/_organizational_label.html.erb
<tr id='<%= dom_id(organizational_label) %>' data-id='<%= organizational_label.id %>' class='organizational_label_row'>
  <td><%= organizational_label.name %></td>
  <td class='controls'>
    <%= link_to t('labels.views.edit_label'), '#', :class => 'icon edit tipit edit_orgnizational_label_button', :title => 'Edit Label', 'data-id'=>organizational_label.id, 'data-name'=>organizational_label.name %>
    <%= link_to t('labels.views.delete_label'), label_path(organizational_label), method: :delete, confirm: t('manage_labels.delete_label_confirmation'), :class => 'icon delete tipit', :title => 'Delete Label' %>
  </td>
</tr>

app/views/labels/add_label.js.erb
<% if @new_label.present? %>
  $('#organizational_label_table').prepend("<%= escape_javascript(render partial: 'labels/organizational_label', locals: {organizational_label: @new_label} ) %>")
  $.hideDialog($("#add_label_div"))
<% end %>
$.a("<%= @message %>")

app/views/labels/create_now.js.erb
if(<%= @status %>){
  $('.label_space .label_list').append("<%= escape_javascript(render partial: 'shared/label', locals: {label_id: @new_label.id, label_name: @new_label.name, checked: true}) if @new_label.present? %>")
  $('.label_space .label_list').prop({scrollTop:$('.label_list').prop('scrollHeight')})
  $('#new_label_field').val('')
  $('#new_label_message').html("")
}else{
  $('#new_label_message').html("<%= escape_javascript(@msg_alert) %>")
}
$("#new_label_button").attr('disabled',false)
$('#new_label_field').removeClass('loading')
$('#new_label_field').focus()

app/views/labels/edit.html.erb
<% provide :sidebar do %>
  <ul class="leftmenu">
    <li class="selected"><%= link_to(t('labels.views.organizational_labels'), labels_path) %></li>
  </ul>
<% end %>

<div class="titlebar titlebarmod">
  <h1>
    <%= "#{current_organization} - #{t('labels.views.edit_label')}" %>
  </h1>
</div>

<div class="pad">  
  <div>
    <%= form_for @label, :method => 'put', validate: true do |f| %>
      <%= render :partial => 'form', :locals => { :button_label => t('labels.views.update'), :f => f } %>
    <% end %>
  </div>
</div>

app/views/labels/edit_label.js.erb
<% if @status.present? && @status %>
  $("#label_<%= @update_label.id%>").remove()
  $('#organizational_label_table').prepend("<%= escape_javascript(render partial: 'labels/organizational_label', locals: {organizational_label: @update_label} ) %>")
  $.hideDialog($("#add_label_div"))
<% end %>
$.a("<%= @message %>")

app/views/labels/index.html.erb
<% provide :sidebar do %>
  <div id="ac_sidebar">
    <div id="upper_sidebar_lists">
    	<button class="red_accent full_width_button" id="add_orgnizational_label_button"><%= t('manage_labels.add_title') %></button>
      <%#= link_to(t('manage_labels.add_button'), new_label_path, class: 'create_label_button') %>
    </div>
  </div>
<% end %>

<div class="titlebar titlebarmod">
  <h1>
    <%= t('manage_labels.title', org: current_organization) %>
    <div id='global_loader'>
      <%= image_tag 'loader.gif'%>
    </div>
  </h1>
</div>

<div class="ac_contact_spread_title">
  <%= t('manage_labels.system_labels') %>
</div>
<div id="ac_contact_spread">
  <table class="listing contact_listing" cellpadding="0" cellspacing="0">
    <tr id="table_header">
      <th><%= t('manage_labels.name') %></th>
    </tr>
    <tbody id="contacts_table">
      <% @system_labels.each do |system_label| %>
        <tr id="<%= dom_id(system_label) %>" data-id="<%= system_label.id %>" class="system_label_row">
          <td class=""><%= system_label.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @system_labels.blank? %>
    <div class="contentpad no_contacts">
      <%= t('contacts.index.no_contacts') %>
    </div>
	<% end %>
</div>

<div class="ac_contact_spread_space">&nbsp;</div>

<div class="ac_contact_spread_title">
  <%= t('manage_labels.organizational_labels') %>
</div>
<div id="ac_contact_spread">
  <table class="listing contact_listing" cellpadding="0" cellspacing="0">
    <tr id="table_header">
      <th><%= t('manage_labels.name') %></th>
      <th class="controls">&nbsp;</th>
    </tr>
    <tbody id="organizational_label_table">
    <% @organizational_labels.each do |org_label| %>
      <%= render 'organizational_label', organizational_label: org_label %>
    <% end %>
    </tbody>
  </table>

  <% if @system_labels.blank? %>
    <div class="contentpad no_contacts">
      <%= t('contacts.index.no_contacts') %>
    </div>
	<% end %>
</div>


<!-- Add a Label Dialog -->
<%= render 'dialogs/add_label', label: Label.new %>

app/views/labels/new.html.erb
<% provide :sidebar do %>
  <ul class="leftmenu">
    <li class="selected"><%= link_to(t('labels.views.organizational_labels'), labels_path) %></li>
  </ul>
<% end %>

<div class="titlebar titlebarmod">
  <h1>
    <%= "#{current_organization} - #{t('labels.views.create_label')}" %>
  </h1>
</div>

<div class="pad">
  <div>
    <%= form_for @label, validate: true do |f| %>
      <%= render :partial => 'form', :locals => { :button_label => t('labels.views.create'), :f => f } %>
    <% end %>
  </div>
</div>