config/routes.rb
Mh::Application.routes.draw do

  resources :movement_indicators, only: [:index, :create] do
    collection do
      get :details
      get :error
    end
  end

  resources :movement_indicator_suggestions do
    collection do
      get :fetch_suggestions
      get :fetch_declined_suggestions
      get :confirm
      post :post_to_infobase
    end
  end


  get "dashboard/index"

  resources :imports, :only => [:show, :new, :create, :update, :destroy, :edit] do
    collection do
      get :download_sample_contacts_csv
      post :create_survey_question
      post :import
    end
  end

  # Interactions
  match 'profile/:id' => 'interactions#show_profile', as: "profile"
  resources :interactions do
    collection do
      get :change_followup_status
      get :reset_edit_form
      get :show_edit_interaction_form
      get :show_new_interaction_form
      get :search_initiators
      get :search_receivers
      get :load_more_interactions
      get :load_more_all_feeds
      get :create_label
      get :set_labels
      get :set_permissions
      get :set_groups
      get :search_leaders
    end
  end

  match 'imports/:id/labels' => 'imports#labels'
  match 'show_assign_search' => 'contacts#show_assign_search'
  match 'show_hidden_questions' => 'contacts#show_hidden_questions'
  match 'show_search_hidden_questions' => 'contacts#show_search_hidden_questions'
  match 'display_sidebar' => 'contacts#display_sidebar'
  match 'display_new_sidebar' => 'contacts#display_new_sidebar'
  match 'show_other_orgs' => 'surveys#show_other_orgs'
  match 'copy_survey' => 'surveys#copy_survey'
  match 'sent_messages' => 'messages#sent_messages'
  match 'search_locate_contact' => 'contacts#search_locate_contact'

  resources :group_labels, :only => [:create, :destroy]

  ActiveAdmin.routes(self)
  ActiveAdmin::ResourceController.class_eval do
    def authenticate_admin!
      unless user_signed_in? && SuperAdmin.find_by_user_id_and_site(current_user.id, 'MissionHub')
        render :file => Rails.root.join(mhub? ? 'public/404_mhub.html' : 'public/404.html'), :layout => false, :status => 404
        false
      end
    end
  end

  resources :groups do
    resources :group_labelings, :only => [:create, :destroy]
    resources :group_memberships, :only => [:create, :destroy] do
      collection do
        get :search
      end
    end
  end

  resources :survey_responses do
    collection do
      get :thanks
      get :facebook
      get :live
    end
  end

  resources :leaders, :only => [:new, :create, :update, :destroy] do
    collection do
      get :search
      put :add_person
    end
  end

  resources :organizational_permissions, :only => :update do
    collection do
      post :move_to
      post :update_all
    end
    member do
      get :set_current
      get :set_primary
    end
  end

  resources :organizational_labels do
    collection do
      post :update_all
    end
  end

  # resources :rejoicables

  resources :saved_contact_searches#, :only => [:show, :create, :edit, :destroy, :index]
  match "/saved_contact_searches/:id" => "saved_contact_searches#update"

  resources :followup_comments, :only => [:index, :create, :destroy]

  resources :contact_assignments, :only => [:create]

  resources :ministries

  resources :sms_keywords, :only => [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      post :accept_twilio
    end
  end

  match "/people" => "contacts#all_contacts"
  match "/allcontacts?assigned_to=unassigned" => "contacts#all_contacts", as: "unassigned_contacts"
  get "/contacts" => redirect("/allcontacts")
  match "/old_directory" => "people#index"
  resources :people, :only => [:show, :create, :edit, :update, :destroy] do
    collection do
      get :export
      get :merge
      post :confirm_merge
      post :do_merge
      get :hide_update_notice
      get :search_ids
      post :bulk_email
      post :bulk_sms
      post :bulk_comment
      get :all
      post :update_permissions
      post :update_permission_status
      post :bulk_delete
      post :bulk_archive
      get :facebook_search
      get :index
    end
    member do
      get :merge_preview
      get :involvement
    end
  end

  resources :labels, :only => [:create, :update, :destroy, :index, :new, :edit] do
    collection do
      post :create_now
      post :add_label
      post :edit_label
    end
  end

  namespace :admin do
    resources :email_templates

  end

  # namespace :admin do
  #   resources :organizations
  # end

  resources :organizations, :only => [:show, :new, :create, :edit, :update, :destroy, :index] do
    collection do
      get :search
      get :thanks
      post :signup
      get :settings
      post :update_settings
      get :cleanup
      get :transfer
      get :available_for_transfer
      get :queue_transfer
      post :do_transfer
      post :archive_contacts
      post :archive_leaders
      post :create_from_crs
      get :api
      get :generate_api_secret
      get :show_hidden_questions
      get :display_sidebar
    end
    member do
      get :update_from_crs
    end
  end

  resources :charts do
    collection do
      get :snapshot
      post :update_snapshot_movements
      post :update_snapshot_range
      get :goal
      get :trend
    end
  end

  resources :surveys, :only => [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get :start
    end
    collection do
      get :index_admin
      get :stop
    end
    resources :questions, controller: "surveys/questions" do
      member do
        put :hide
        put :unhide
      end
      collection do
        post :reorder
      end
    end
  end

  match "/dashboard" => "dashboard#index"
  get "welcome/index"
  get "welcome/duplicate"
  match 'tutorials' => "welcome#tutorials"
  get "/test" => "welcome#test"

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    match "/sign_in", to: "sessions#new"
    match "/sign_out", to: "sessions#destroy"
    match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'
    match '/users/auth/facebook_mhub/callback', to: 'users/omniauth_callbacks#facebook_mhub'
  end
  match '/auth/facebook/logout' => 'application#facebook_logout', as: :facebook_logout

  match "/application.manifest" => OFFLINE

  post "sms/mo"
  get "sms/mo"

  match "/allcontacts" => "contacts#all_contacts", as: "all_contacts"
  match "/mycontacts" => "contacts#my_contacts", as: "my_contacts"
  match "/my_contacts_all" => "contacts#my_contacts_all", as: "my_contacts_all"
  resources :contacts, :only => [:show, :create, :edit, :update, :destroy, :index] do
    collection do
      get :all_contacts
      get :my_contacts
      get :mine
      get :mine_all
      get :contacts_all
      post :send_reminder
      put :create_from_survey
      delete :destroy
      post :bulk_destroy
      post :send_vcard
      get :send_bulk_vcard
      get :import_contacts
      post :csv_import
      get :download_sample_contacts_csv
      get :search_by_name_and_email
      get :auto_suggest_send_email
      get :auto_suggest_send_text
    end
  end

  resources :vcards, :only => [:create] do
    collection do
      get :bulk_create
    end
  end

  namespace :api do
    scope '(/:version)', version: /v\d+?/ do  #module: :api
      resources :people do
        collection do
          get :leaders
        end
      end
      resources :friends
      get 'contacts/search' => 'contacts#search'
      resources :contacts do
        resource :photo
      end
      get "contact_assignments/list_leaders" => "contact_assignments#list_leaders"
      get "contact_assignments/list_organizations" => "contact_assignments#list_organizations"
      resources :contact_assignments
      resources :followup_comments
      resources :interactions
      resources :roles
      resources :permissions
      resources :organizational_labels
      resources :organizational_permissions
      resources :organizations
    end
  end

  namespace :apis do

    api_version(module: 'V3', header: {name: 'API-VERSION', value: 'v3'}, parameter: {name: "version", value: 'v3'}, path: {value: 'v3'}) do
      resources :contact_assignments do
        collection do
          put :bulk_update
          delete :bulk_destroy
        end
      end
      resources :people do
        collection do
          get :ids
          delete :bulk_destroy
        end
      end
      resources :organizations
      resources :answers
      resources :surveys do
        resources :questions
      end
      resources :questions
      resources :followup_comments
      resources :roles
      resources :organizational_roles
      resources :interactions
      resources :interaction_types
      resources :labels
      resources :permissions
      resources :organizational_labels do
        collection do
          post :bulk
          post :bulk_create
          delete :bulk_destroy
        end
      end
      resources :organizational_permissions do
        collection do
          post :bulk
          post :bulk_create
          post :bulk_archive
          delete :bulk_destroy
        end
      end
    end
  end

  root to: "welcome#index"
#  match 'home' => 'welcome#home', as: 'user_root' ---- LOOK FOR THIS IN application_controller.rb
  match 'wizard' => 'welcome#wizard', as: 'wizard'
  match 'terms' => 'welcome#terms', as: 'terms'
  match 'privacy' => 'welcome#privacy', as: 'privacy'

  # SMS keyword state transitions
  match '/admin/sms_keywords/:id/t/:transition' => 'admin/sms_keywords#transition', as: 'sms_keyword_transition'
  match '/admin/sms_keywords/approve'

  match '/admin/organizations/:id/t/:transition' => 'admin/organizations#transition', as: 'organization_transition'
  match '/admin/organizations/approve'

  # Map keyword responses with phone numbers
  match 'c/:keyword(/:received_sms_id)' => 'survey_responses#new', as: 'contact_form'
  match 'm/:received_sms_id' => 'survey_responses#new'

app/models/group.rb
class Group < ActiveRecord::Base
  
  has_many :group_labelings, dependent: :destroy
  has_many :group_labels, through: :group_labelings
  has_many :group_memberships, dependent: :destroy
  has_many :involved, through: :group_memberships, source: :involved
  has_many :members, through: :group_memberships, source: :member
  has_many :leaders, through: :group_memberships, source: :leader
  belongs_to :organization
  
  validates_presence_of :name, :location, :meets
  
  def to_s
    name
  end
  
  def public_signup?
    list_publicly? && !approve_join_requests?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :ensure_current_org
  before_filter :get_group
  before_filter :leader_needed, :only => [:create, :new]

  def index
    if params[:search].present? && params[:search][:meta_sort].present?
      sort_query = params[:search][:meta_sort].gsub('.',' ')
    	if ['name'].any?{ |i| sort_query.include?(i) }
  			order_query = sort_query.gsub('name','groups.name')
  		end
    else
      order_query = "groups.name"
    end

    @groups = current_organization.groups.order(order_query)
    @q = current_organization.groups.where('1 <> 1').search(params[:search])

    people_ids = GroupMembership.where(group_id: @groups.collect(&:id)).collect(&:person_id)
    @people = current_organization.people.where(id: people_ids)
    @all_people_with_phone_number = @people.includes(:primary_phone_number).where('phone_numbers.number is not NULL').uniq
    @all_people_with_email = @people.where(id: people_ids).includes(:primary_email_address).where('email_addresses.email is not NULL').uniq
  end

  def show
    permissions_for_assign

    @group = Present(@group)
    @people = current_organization.all_people.get_from_group(@group.id).uniq

    if params[:search].present? && params[:search][:meta_sort].present?
      sort_query = params[:search][:meta_sort].gsub('.',' ')
      @people = @people.includes(:group_memberships) if sort_query.include?('permission')
			order_string = sort_query.gsub('first_name','people.first_name')
                               .gsub('permission','group_memberships.permission')
    else
      order_string = "people.first_name"
    end

    @q = @people.where('1 <> 1').search(params[:search])
    @people = @people.order(order_string)
    @all_people_with_phone_number = @people.includes(:primary_phone_number).where('phone_numbers.number is not NULL')
    @all_people_with_email = @people.includes(:primary_email_address).where('email_addresses.email is not NULL')

    authorize! :read, @group
  end

  def edit
    authorize! :edit, @group
  end

  def update
    authorize! :update, @group
    if @group.update_attributes(params[:group])
      redirect_to @group
    else
      redirect_to :back
    end
  end

  def new
    index
    @group = current_organization.groups.new
  end

  def create
    @group = current_organization.groups.create(params[:group])
    if @group.valid?
      redirect_to @group
    else
      render :new
    end
  end

  def destroy
    authorize! :destroy, @group
    @group.destroy
    redirect_to groups_path
  end

  protected

    def get_group
      begin
        @group = current_organization.groups.find(params[:id]) if params[:id]
      rescue ActiveRecord::RecordNotFound
        @group = nil
        flash[:error] = "Group not found"
      end
    end

    def leader_needed
      authorize! :lead, current_organization
    end

end

app/views/groups/_form.html.erb
<%= form_for @group, validate: true do |f| %>
<div class="customform group_form">
  <div class="item">
    <div class="group_label">
      <%= f.label :name %>
    </div>
    <div class="field">
      <%= f.text_field :name %>
    </div>
  </div>


  <div class="item">
    <div class="group_label">
      <%= f.label :location %>
      <div class="icon help tipitright help_bubble_keyword" title="<%= t('groups.form.location_tip') %>"></div>
    </div>
    <div class="field">
      <%= f.text_area :location, :class => "location" %>
    </div>
  </div>


  <div class="item" style="display:none;">
    <%= f.check_box :list_publicly %>
    <%= f.label :list_publicly %>
    <div class="icon help tipitright help_bubble_keyword" title="<%= t('groups.form.list_publicly_tip') %>"></div>
  </div>


  <div class="item" style="display:none; <%#= 'display:none' if !@group.list_publicly? %>">
    <%= f.check_box :approve_join_requests %>
    <%= f.label :approve_join_requests %>
    <div class="icon help tipitright help_bubble_keyword" title="<%= t('.approve_join_tip') %>"></div>
  </div>

  <div class="item_half">
    <div class="group_label">
      <%= f.label :meets %>
    </div>
    <div class="field">
      <%= f.select :meets, [[t('weekly'), 'weekly'], [t('monthly'), 'monthly'], [t('sporadically'), 'sporadically']] %>
    </div>
  </div>


  <div class="item_half_right" style="<%= 'display:none' if @group.meets == 'sporadically' %>">
    <div class="group_label">
      <div class="day_of_week_div regular" style="<%= 'display:none' unless @group.meets == 'weekly' || @group.meets.blank?  %>">
        <%= f.label :meeting_day, t('.meets_on') %>
      </div>
      <div class="day_of_month_div regular" style="<%= 'display:none' unless @group.meets == 'monthly' %>">
        <%= f.label :meeting_day, t('.meets_on_the') %>
      </div>
    </div>
    <div class="field">
      <div class="day_of_week_div regular" style="<%= 'display:none' unless @group.meets == 'weekly' || @group.meets.blank? %>">
        <% selected = (@group.meets == 'weekly') ? @group.meeting_day : 0 %>
        <%= select_tag :day_of_week, options_for_select(t('date.day_names').collect.with_index {|d, i| [d, i]}, selected) %>
      </div>
      <div class="day_of_month_div regular" style="<%= 'display:none' unless @group.meets == 'monthly' %>">
        <% selected = (@group.meets == 'monthly') ? @group.meeting_day : 0 %>
        <%= select_tag :day_of_month, options_for_select((1..31).collect {|i| [i.ordinalize, i]}, selected) %>
        <%= t('.of_month') %>
      </div>
    </div>
    <%= f.hidden_field :meeting_day %>
  </div>


  <div class="item_half regular" style="<%= 'display:none' if @group.meets == 'sporadically' %>">
    <div class="group_label">
      From
    </div>
    <div class="field">
      <%= f.select :start_time, times(6.hours.to_i, 22.hours.to_i) %>
    </div>
  </div>


  <div class="item_half_right regular" style="<%= 'display:none' if @group.meets == 'sporadically' %>">
    <div class="group_label">
      To
    </div>
    <div class="field">
      <%= f.select :end_time, times(7.hours.to_i, 22.hours.to_i) %>
    </div>
  </div>

  <br/>

  <div class="item formactions">
    <%= f.submit %><%= link_to(t('.back'), :back, :class=> "cancel")%>
  </div>
</div>
<% end %>

app/views/groups/_group.html.erb
<%- group_presenter = Present(group) %>
<tr data-id="<%= group.id %>">
	<td class="handle_container">
    <%= image_tag('grippy.png', class: 'handle' ) %>
	</td>
  <td nowrap="nowrap" class="checkbox_cell">
    <%= check_box_tag 'gids[]', group.id, false, id: "gids_#{group.id}", class: 'id_checkbox group_checkbox' %>
    <%- current_organization.people.get_from_group(group.id).each do |person| %>
      <%= check_box_tag 'ids[]', person.id, false, 'data-id'=>person.id, 'data-number'=>person.pretty_phone_number, id: "ids_#{person.id}", class: "id_checkbox contact_checkbox gids_#{group.id} hidden", 'data-name' => "#{person.first_name} #{person.last_name}", 'data-email'=>person.email %>
    <% end %>
  </td>
  <td class="group_name_column">
    <%= link_to(group.name, group) %>
  </td>
  <td>
    <% if !group.list_publicly %>
      <%= image_tag('lock.gif', class: 'privategroup' ) %>
    <% end %>
  </td>
  <td>
    <%= current_organization.all_people.get_from_group(group.id).collect(&:name).count %>
  </td>
  <td>
    <%= current_organization.all_people.get_leaders_from_group(group.id).collect(&:name).join(", ") %>
  </td>
  <td class="controls" align="right">
    <%= link_to("Show", group, :class => "icon magnify tipitleft", :title => t('nav.view_details')) %>
  </td>
</tr>

app/views/groups/_group_member_sidebar.html.erb
<% provide :sidebar do %>
  <div id="ac_sidebar">
    <div id="upper_sidebar_lists">
      <%= link_to raw("<button class='red_accent full_width_button'>#{t('groups.show.back_to_list')}</button>"), groups_path %>
      <%= link_to raw("<button class='action_gray full_width_button'>#{t('groups.show.edit_group')}</button>"), edit_group_path(@group) %>
      <%= link_to raw("<button class='action_gray full_width_button'>#{t('groups.show.delete_group')}</button>"), group_path(@group), method: :delete, confirm: t('groups.show.confirm_delete_group') %>
    </div>
  	<div id="group_member_sidebar">
      <div class="title_with_bg">
        <%= t('groups.show.details') %>
      </div>
      <div class="information">
        <div>
          <div class="title"><%= t('groups.index.leaders') %>:</div>
          <div class="content"><%= @group.leaders_names %></div>
        </div>
        <br/>
        <div>
          <div class="title"><%= t('groups.show.location') %>:</div>
          <div class="content"><%= link_to(@group.location, "http://www.google.com/maps?q=#{@group.location}", target: '_blank') %></div>
        </div>
        <br/>
        <div>
          <div class="title"><%= t('groups.show.meets') %>:</div>
          <div class="content"><%= raw(@group.meets_at) %></div>
        </div>
      </div>
      <div>
        <%= link_to(image_tag("http://maps.googleapis.com/maps/api/staticmap?center=#{@group.location}&zoom=15&size=180x180&markers=color:blue|label:G|#{@group.location}&sensor=false"), "http://www.google.com/maps?q=#{@group.location}", target: '_blank', class: "nostyle") %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/_group_sidebar.html.erb
<% provide :sidebar do %>
  <div id="ac_sidebar">
    <div id="upper_sidebar_lists">
      <%= link_to raw("<button class='red_accent full_width_button'>#{t('groups.index.add_a_group')}</button>"), new_group_path %>
    </div>
  	<div class="leftmenu">
      <ul class="ac_dropdown_list">
      	<li class="ac_dropdown_list_header">
          <%= link_to(t('groups.see_all'), groups_path) %>&nbsp;(<%= current_organization.groups.count %>)
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/groups/_label.html.erb
<li class="entry label <%= 'selected_entry' if params[:label].to_i == label.id %>" data-id="<%= label.id %>">
  <%= link_to label, groups_path(label: label) %>
  <%= link_to(image_tag('delete.png', title: 'Remove Group Label', class: 'tip'), group_label_path(label), method: :delete, remote: true, class: 'delete_icon delete_label', data: { confirm: t('.delete_confirm', label: label) }) %>
</li>

app/views/groups/_label_form.html.erb
<div id="new_label" style="display:none" title="<%= t('groups.add_a_label_title') %>">
  <%= form_for GroupLabel.new, remote: true, validate: true do |f| %>
    <div class="item">
      <div class="group_label">
        <%= t('groups.new_label_prompt') %>:
      </div>
      <div class="field al_center">
        <%= f.text_field :name, :autocomplete => 'off' %>
        <%= spinner('new_label') %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/_person.html.erb
<tr id="<%= dom_id(person) %>" class="person_row" data-name="<%= person.name %>" data-email="<%= person.email %>" data-id="<%= person.id %>">
  <td nowrap="nowrap" class="checkbox_cell">
    <%= check_box_tag 'ids[]', person.id, false, 'data-id'=>person.id, 'data-number'=>person.pretty_phone_number, id: "ids_#{person.id}", class: 'id_checkbox contact_checkbox group_contact_checkbox', 'data-name' => "#{person.first_name} #{person.last_name}", 'data-email'=>person.email %>
  </td>
  <td class="name"><%= person.name %></td>
  <td class="email"><%= mail_to(person.email) if person.email.present? %></td>
  <td class="phone_number"><%= person.pretty_phone_number %></td>
  <td>
    <%= t(group_membership.role) if group_membership.role.present? %>
    <% if person.is_archived?(current_organization) %>
      <span class="archived_group_label">&nbsp<%= t('general.archived') %>&nbsp</span>
    <% end %>
  </td>
  <td class="controls" align="right">
    <%= link_to(t('general.delete'), group_group_membership_path(@group, group_membership), :method => :delete, :remote => true, :class => "icon tipitleft delete", :confirm => t('.remove_confirm', name: person), :title => t('groups.delete_group_member')) %></td>
</tr>

app/views/groups/edit.html.erb
<%= render partial: 'groups/group_sidebar'%>

<div class="titlebar titlebarmod"><h1><%= t('.edit_group', group: @group) %></h1></div>

<!-- Add Group Form -->
<%= render 'form' %>

<!-- Group Label Dialog -->
<%= render 'dialogs/add_group_label'%>

app/views/groups/index.html.erb
<%= render partial: 'groups/group_sidebar'%>

<div class="titlebar titlebarmod">
  <h1>
    <%= t('.group_list', org: current_organization.to_s) %>
    <%= t('.labeled_with', label: @label) if @label %>
    <div id='global_loader'>
      <%= image_tag 'loader.gif'%>
    </div>
  </h1>
</div>

<div id="ac_button_bar">
	<ul class="button_bar">
		<li class="action_lightblue btn_left">
		  <%= link_to t("people.index.send_sms"), "#", id: "action_menu_text" %>
		</li>
	</ul>
	<ul class="button_bar">
		<li class="action_lightblue btn_right">
		  <%= link_to t("people.index.send_email"), "#", id: "action_menu_email" %>
		</li>
	</ul>
</div>
<br/>

<div id="ac_contact_spread">
  <span style="display:none" id="drag_helper_text_one"><%= t('.assign_to_label', count: 1) %></span>
  <span style="display:none" id="drag_helper_text_other"><%= t('.assign_to_label', count: 0) %></span>

  <table class="listing contact_listing" cellpadding="0" cellspacing="0">
    <tr id="table_header">
    	<th>&nbsp;</th>
      <th class="checkbox_cell header_checkbox">
        <%= check_box_tag 'check_all_groups', true, false %>
      </th>
      <th class="group_name_column"><%= sort_link @q, :name, t('.group_name'), params %></th>
      <th>&nbsp;</th>
      <th><%= t('.members') %></th>
      <th><%= t('.leaders') %></th>
      <th>&nbsp;</th>
    </tr>
    <tbody id="groups_table">
      <% @groups.each do |group| %>
        <%= render partial: 'groups/group', locals: {group: group}%>
      <% end %>
    </tbody>
  </table>

  <% if @groups.blank? %>
    <div class="contentpad no_contacts">
      <%= t('.no_groups') %>
    </div>
	<% end %>
</div>

<!-- Message Dialog -->
<%= render 'dialogs/bulk_send_msg' %>

<!-- Group Label Dialog -->
<%= render 'dialogs/add_group_label'%>

app/views/groups/new.html.erb
<%= render partial: 'groups/group_sidebar'%>

<div class="titlebar titlebarmod"><h1><%= t('.new_group') %></h1></div>

<!-- Add Group Form -->
<%= render 'form' %>

<!-- Group Label Dialog -->
<%= render 'dialogs/add_group_label'%>

app/views/groups/show.html.erb
<%= render partial: 'groups/group_member_sidebar'%>

<div class="titlebar titlebarmod">
  <h1>
    <%= t(".page_title", :group_name => @group) %>
    <div id='global_loader'>
      <%= image_tag 'loader.gif'%>
    </div>
  </h1>
</div>

<div id="ac_button_bar">
	<ul class="button_bar">
		<li class="action_lightblue">
      <%= link_to(t('.add_member'), "#", class: "add_group_member", "data-desc"=>t('group_memberships.form.add_a_member'), "data-role"=>"member") %>
		</li>
	</ul>

	<ul class="button_bar">
		<li class="action_lightblue">
      <%= link_to(t('.add_leader'), "#", class: "add_group_leader", "data-desc"=>t('group_memberships.form.add_a_leader'), "data-role"=>"leader") %>
		</li>
	</ul>

	<ul class="button_bar">
		<li class="action_lightblue btn_left">
		  <%= link_to t("people.index.send_sms"), "#", id: "action_menu_text" %>
		</li>
	</ul>

	<ul class="button_bar">
		<li class="action_lightblue btn_right">
		  <%= link_to t("people.index.send_email"), "#", id: "action_menu_email" %>
		</li>
	</ul>

	<ul class="button_bar">
		<li class="action_lightblue">
      <%= link_to(t('people.index.group_comment'), "#", id: "action_menu_comment") %>
		</li>
	</ul>
</div>
<br/>

<div id="ac_contact_spread">
  <table class="listing contact_listing" cellpadding="0" cellspacing="0">
    <tr id="table_header">
      <th class="checkbox_cell header_checkbox">
        <%= check_box_tag 'check_all', true, false %>
      </th>
      <th><%= sort_link @q, :first_name, t('.name'), params %></th>
      <th><%= t('.email') %></th>
      <th><%= t('.phone') %></th>
      <th>
        <% if params[:search] && params[:search][:meta_sort].include?('asc') %>
          <%=raw sort_link(@q, :role, t('.role'), params).gsub('asc','desc') %>
        <% else %>
          <%= sort_link @q, :role, t('.role'), params %>
        <% end %>
      </th>
      <th>&nbsp;</th>
    </tr>
    <tbody id="group_table">
      <% @people.each do |person| %>
        <%= render 'groups/person', person: person, group_membership: person.group_memberships.where(group_id: @group.id).first %>
      <% end %>
    </tbody>
  </table>

  <% if @people.blank? %>
    <div class="contentpad no_contacts">
      <%= t('groups.index.no_group_members') %>
    </div>
	<% end %>
</div>


<%= render 'group_memberships/form' %>

<!-- Add Contact Dialog -->
<%= render 'dialogs/add_contact', person: Person.new %>

<!-- Message Dialog -->
<%= render 'dialogs/bulk_send_msg' %>

<!-- Group Label Dialog -->
<%= render 'dialogs/add_group_label'%>

<!-- Group Label Dialog -->
<%= render 'dialogs/bulk_add_comment'%>