config/routes.rb
Mh::Application.routes.draw do

  resources :movement_indicators, only: [:index, :create] do
    collection do
      get :details
      get :error
    end
  end

  resources :movement_indicator_suggestions do
    collection do
      get :fetch_suggestions
      get :fetch_declined_suggestions
      get :confirm
      post :post_to_infobase
    end
  end


  get "dashboard/index"

  resources :imports, :only => [:show, :new, :create, :update, :destroy, :edit] do
    collection do
      get :download_sample_contacts_csv
      post :create_survey_question
      post :import
    end
  end

  # Interactions
  match 'profile/:id' => 'interactions#show_profile', as: "profile"
  resources :interactions do
    collection do
      get :change_followup_status
      get :reset_edit_form
      get :show_edit_interaction_form
      get :show_new_interaction_form
      get :search_initiators
      get :search_receivers
      get :load_more_interactions
      get :load_more_all_feeds
      get :create_label
      get :set_labels
      get :set_permissions
      get :set_groups
      get :search_leaders
    end
  end

  match 'imports/:id/labels' => 'imports#labels'
  match 'show_assign_search' => 'contacts#show_assign_search'
  match 'show_hidden_questions' => 'contacts#show_hidden_questions'
  match 'show_search_hidden_questions' => 'contacts#show_search_hidden_questions'
  match 'display_sidebar' => 'contacts#display_sidebar'
  match 'display_new_sidebar' => 'contacts#display_new_sidebar'
  match 'show_other_orgs' => 'surveys#show_other_orgs'
  match 'copy_survey' => 'surveys#copy_survey'
  match 'sent_messages' => 'messages#sent_messages'
  match 'search_locate_contact' => 'contacts#search_locate_contact'

  resources :group_labels, :only => [:create, :destroy]

  ActiveAdmin.routes(self)
  ActiveAdmin::ResourceController.class_eval do
    def authenticate_admin!
      unless user_signed_in? && SuperAdmin.find_by_user_id_and_site(current_user.id, 'MissionHub')
        render :file => Rails.root.join(mhub? ? 'public/404_mhub.html' : 'public/404.html'), :layout => false, :status => 404
        false
      end
    end
  end

  resources :groups do
    resources :group_labelings, :only => [:create, :destroy]
    resources :group_memberships, :only => [:create, :destroy] do
      collection do
        get :search
      end
    end
  end

  resources :survey_responses do
    collection do
      get :thanks
      get :facebook
      get :live
    end
  end

  resources :leaders, :only => [:new, :create, :update, :destroy] do
    collection do
      get :search
      put :add_person
    end
  end

  resources :organizational_permissions, :only => :update do
    collection do
      post :move_to
      post :update_all
    end
    member do
      get :set_current
      get :set_primary
    end
  end

  resources :organizational_labels do
    collection do
      post :update_all
    end
  end

  # resources :rejoicables

  resources :saved_contact_searches#, :only => [:show, :create, :edit, :destroy, :index]
  match "/saved_contact_searches/:id" => "saved_contact_searches#update"

  resources :followup_comments, :only => [:index, :create, :destroy]

  resources :contact_assignments, :only => [:create]

  resources :ministries

  resources :sms_keywords, :only => [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      post :accept_twilio
    end
  end

  match "/people" => "contacts#all_contacts"
  match "/allcontacts?assigned_to=unassigned" => "contacts#all_contacts", as: "unassigned_contacts"
  get "/contacts" => redirect("/allcontacts")
  match "/old_directory" => "people#index"
  resources :people, :only => [:show, :create, :edit, :update, :destroy] do
    collection do
      get :export
      get :merge
      post :confirm_merge
      post :do_merge
      get :hide_update_notice
      get :search_ids
      post :bulk_email
      post :bulk_sms
      post :bulk_comment
      get :all
      post :update_permissions
      post :update_permission_status
      post :bulk_delete
      post :bulk_archive
      get :facebook_search
      get :index
    end
    member do
      get :merge_preview
      get :involvement
    end
  end

  resources :labels, :only => [:create, :update, :destroy, :index, :new, :edit] do
    collection do
      post :create_now
      post :add_label
      post :edit_label
    end
  end

  namespace :admin do
    resources :email_templates

  end

  # namespace :admin do
  #   resources :organizations
  # end

  resources :organizations, :only => [:show, :new, :create, :edit, :update, :destroy, :index] do
    collection do
      get :search
      get :thanks
      post :signup
      get :settings
      post :update_settings
      get :cleanup
      get :transfer
      get :available_for_transfer
      get :queue_transfer
      post :do_transfer
      post :archive_contacts
      post :archive_leaders
      post :create_from_crs
      get :api
      get :generate_api_secret
      get :show_hidden_questions
      get :display_sidebar
    end
    member do
      get :update_from_crs
    end
  end

  resources :charts do
    collection do
      get :snapshot
      post :update_snapshot_movements
      post :update_snapshot_range
      get :goal
      get :trend
    end
  end

  resources :surveys, :only => [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get :start
    end
    collection do
      get :index_admin
      get :stop
    end
    resources :questions, controller: "surveys/questions" do
      member do
        put :hide
        put :unhide
      end
      collection do
        post :reorder
      end
    end
  end

  match "/dashboard" => "dashboard#index"
  get "welcome/index"
  get "welcome/duplicate"
  match 'tutorials' => "welcome#tutorials"
  get "/test" => "welcome#test"

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    match "/sign_in", to: "sessions#new"
    match "/sign_out", to: "sessions#destroy"
    match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'
    match '/users/auth/facebook_mhub/callback', to: 'users/omniauth_callbacks#facebook_mhub'
  end
  match '/auth/facebook/logout' => 'application#facebook_logout', as: :facebook_logout

  match "/application.manifest" => OFFLINE

  post "sms/mo"
  get "sms/mo"

  match "/allcontacts" => "contacts#all_contacts", as: "all_contacts"
  match "/mycontacts" => "contacts#my_contacts", as: "my_contacts"
  match "/my_contacts_all" => "contacts#my_contacts_all", as: "my_contacts_all"
  resources :contacts, :only => [:show, :create, :edit, :update, :destroy, :index] do
    collection do
      get :all_contacts
      get :my_contacts
      get :mine
      get :mine_all
      get :contacts_all
      post :send_reminder
      put :create_from_survey
      delete :destroy
      post :bulk_destroy
      post :send_vcard
      get :send_bulk_vcard
      get :import_contacts
      post :csv_import
      get :download_sample_contacts_csv
      get :search_by_name_and_email
      get :auto_suggest_send_email
      get :auto_suggest_send_text
    end
  end

  resources :vcards, :only => [:create] do
    collection do
      get :bulk_create
    end
  end

  namespace :api do
    scope '(/:version)', version: /v\d+?/ do  #module: :api
      resources :people do
        collection do
          get :leaders
        end
      end
      resources :friends
      get 'contacts/search' => 'contacts#search'
      resources :contacts do
        resource :photo
      end
      get "contact_assignments/list_leaders" => "contact_assignments#list_leaders"
      get "contact_assignments/list_organizations" => "contact_assignments#list_organizations"
      resources :contact_assignments
      resources :followup_comments
      resources :interactions
      resources :roles
      resources :permissions
      resources :organizational_labels
      resources :organizational_permissions
      resources :organizations
    end
  end

  namespace :apis do

    api_version(module: 'V3', header: {name: 'API-VERSION', value: 'v3'}, parameter: {name: "version", value: 'v3'}, path: {value: 'v3'}) do
      resources :contact_assignments do
        collection do
          put :bulk_update
          delete :bulk_destroy
        end
      end
      resources :people do
        collection do
          get :ids
          delete :bulk_destroy
        end
      end
      resources :organizations
      resources :answers
      resources :surveys do
        resources :questions
      end
      resources :questions
      resources :followup_comments
      resources :roles
      resources :organizational_roles
      resources :interactions
      resources :interaction_types
      resources :labels
      resources :permissions
      resources :organizational_labels do
        collection do
          post :bulk
          post :bulk_create
          delete :bulk_destroy
        end
      end
      resources :organizational_permissions do
        collection do
          post :bulk
          post :bulk_create
          post :bulk_archive
          delete :bulk_destroy
        end
      end
    end
  end

  root to: "welcome#index"
#  match 'home' => 'welcome#home', as: 'user_root' ---- LOOK FOR THIS IN application_controller.rb
  match 'wizard' => 'welcome#wizard', as: 'wizard'
  match 'terms' => 'welcome#terms', as: 'terms'
  match 'privacy' => 'welcome#privacy', as: 'privacy'

  # SMS keyword state transitions
  match '/admin/sms_keywords/:id/t/:transition' => 'admin/sms_keywords#transition', as: 'sms_keyword_transition'
  match '/admin/sms_keywords/approve'

  match '/admin/organizations/:id/t/:transition' => 'admin/organizations#transition', as: 'organization_transition'
  match '/admin/organizations/approve'

  # Map keyword responses with phone numbers
  match 'c/:keyword(/:received_sms_id)' => 'survey_responses#new', as: 'contact_form'
  match 'm/:received_sms_id' => 'survey_responses#new'

app/controllers/api3/v3/surveys_controller.rb
class Api3::V3::SurveysController < Api3::V3::BaseController
  before_filter :get_survey, only: [:show, :update, :destroy]

  def index
    order = params[:order] || 'title'

    list = add_includes_and_filters(surveys, order: order)

    render json: list,
           callback: params[:callback],
           scope: includes
  end

  def show
    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  def create
    survey = surveys.new(params[:survey])

    if survey.save
      render json: survey,
             status: :created,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :bad_request,
             callback: params[:callback]
    end
  end

  def update
    if @survey.update_attributes(params[:survey])
      render json: @survey,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :bad_request,
             callback: params[:callback]
    end

  end

  def destroy
    @survey.destroy

    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  private

  def surveys
    current_organization.surveys
  end

  def get_survey
    @survey = add_includes_and_filters(surveys)
                .find(params[:id])

  end

  def available_includes
    [:keyword, :questions]
  end

end

app/controllers/apis/v3/surveys_controller.rb
class Apis::V3::SurveysController < Apis::V3::BaseController
  before_filter :get_survey, only: [:show, :update, :destroy]

  def index
    order = params[:order] || 'title'

    list = add_includes_and_order(surveys, order: order)

    render json: list,
           callback: params[:callback],
           scope: {include: includes, since: params[:since]}
  end

  def show
    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  def create
    survey = surveys.new(params[:survey])

    if survey.save
      render json: survey,
             status: :created,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :unprocessable_entity,
             callback: params[:callback]
    end
  end

  def update
    if @survey.update_attributes(params[:survey])
      render json: @survey,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :unprocessable_entity,
             callback: params[:callback]
    end

  end

  def destroy
    @survey.destroy

    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  private

  def surveys
    current_organization.surveys
  end

  def get_survey
    @survey = add_includes_and_order(surveys)
                .find(params[:id])

  end

  def available_includes
    [:keyword, :questions]
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :set_keyword_cookie, only: :start
  before_filter :prepare_for_mobile, only: [:start, :stop, :index]
  skip_before_filter :authenticate_user!
  skip_before_filter :check_url
  load_and_authorize_resource except: [:start, :stop, :index]

  require 'api_helper'
  include ApiHelper

  def index_admin
    @organization = current_person.organization_from_id(params[:org_id]) || current_organization
    authorize! :manage, @organization
    @surveys = @organization.surveys
  end

  def index
    # authenticate_user! unless params[:access_token] && params[:org_id]
    @title = "Pick A Survey"
    if current_user
      @organization = current_person.organization_from_id(params[:org_id]) || current_organization
      @surveys = @organization ? @organization.self_and_children_surveys : nil

      respond_to do |wants|
        wants.html { render 'index_admin' }
        wants.mobile
      end
    else
      return render_404
    end
  end

  def edit

  end

  def new

  end

  def destroy
    @survey.destroy
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.js {render :nothing => true}
    end
  end

  def show_other_orgs
    org_ids = (current_person.admin_of_org_ids - [current_organization.id]).uniq
    @managed_orgs = Organization.where(id: org_ids)
    if params[:keyword]
      @managed_orgs = @managed_orgs.where("name LIKE ? OR name = ?","%#{params[:keyword]}%", params[:keyword])
    end
    @managed_orgs = @managed_orgs.order('name')
  end

  def copy_survey
    @survey = current_organization.surveys.find(params[:survey_id])
    @receiving_org = Organization.find(params[:organization_id])
    @status = 'failed'

    if @survey && @receiving_org
      if @receiving_org.surveys.where(title: @survey.title).present?
        @status = 'duplicate'
      else
        new_survey = @receiving_org.surveys.new(@survey.attributes)
        if new_survey.save
          @survey.survey_elements.each do |q|
            new_question = new_survey.survey_elements.new(q.attributes)
            new_question.save
          end
          @status = 'copied'
        end
      end
    end
  end

  def update
    if @survey.update_attributes(params[:survey])
      redirect_to index_admin_surveys_path
    else
      render :edit
    end
  end

  def create
    @survey = current_organization.surveys.new(params[:survey])
    if @survey.save
      redirect_to index_admin_surveys_path
    else
      current_organization.surveys -= [@survey]
      render :new
    end
  end

  # Enter survey mode
  def start
    unless mhub? #|| Rails.env.test?
      redirect_to start_survey_url(@survey, host: APP_CONFIG['public_host'], port: APP_CONFIG['public_port'])
      return false
    end
    cookies[:survey_mode] = 1
    redirect_to sign_out_url(next: short_survey_url(@survey.id))
    #redirect_to short_survey_url(@survey.id)
  end

  # Exit survey mode
  def stop
    cookies[:survey_mode] = nil
    cookies[:keyword] = nil
    cookies[:survey_id] = nil
    redirect_to(request.referrer ? :back : 'http://www.missionhub.com')
  end


end

app/views/surveys/_form.html.erb
<%= form_for(@survey, validate: true, html: {id: 'survey_form'}) do |f| %>
  <%= error_messages_for :survey %>

  <div class="stepwrap rwidth">
    <div class="stepcontent">
      <div class="field">
        <%= f.check_box :is_frozen %><%= t('.freeze') %>
      </div>
    </div>
  </div>

  <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <label for="survey_label">
        <%= t('.login_paragraph') + ": " + t('.login_paragraph_tip') %>
      </label>
      <div class="field">
        <%= f.text_area :login_paragraph, rows: 3, value: raw(@survey.login_paragraph.present? ? @survey.login_paragraph : t('sessions.new.login_paragraph_mhub')) %>
      </div>
    </div>
  </div>

  <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <label for="survey_label">
        <%= t('.title') + ": " + t('.title_tip') %>
      </label>
      <div class="field">
        <%= f.text_field :title, :placeholder => t('.title_placeholder') %>
      </div>
    </div>
  </div>
  <!-- <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <div class="field">
        <label for="survey_initial_response">
          <%= raw(t('surveys.form.initial_response')) %>
          <%= tip(t('surveys.form.post_survey_why')) %>
        </label>
        <%#= f.text_area :initial_response, rows: 3 %>
      </div>
    </div>
  </div> -->

  <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <label for="survey_label">
        <%= t('.post_survey_message') %>
      </label>
      <div class="field">
        <%= f.text_area :post_survey_message, rows: 3, :placeholder => t('.post_survey_placeholder') %>
      </div>
    </div>
  </div>

  <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <label for="survey_label">
        <%= t('.terminology') %>
      </label>
      <div class="field">
        <%= f.text_field :terminology %>
      </div>
    </div>
  </div>

  <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <label for="survey_label">
        <%= t('.login_option') %>
        <br />
        <strong style="color:red">NOTE: Facebook login for survey mode is currently disabled due to a problem we're having with facebook. You can still do surveys,
          just the facebook login will be skipped. We will re-enable it as soon as we get it working.</strong>
      </label>
      <div class="field">
        <%= f.radio_button :login_option, 0, :checked => true %> <%= t('.default_login_option') %><br/>
        <%= f.radio_button :login_option, 1 %> <%= t('.fb_only_login_option') %><br/>
        <%= f.radio_button :login_option, 2 %> <%= t('.skip_fb_login_option') %><br/>
        <%= f.radio_button :login_option, 3 %> <%= t('.no_fb_login_option') %>
      </div>
    </div>
  </div>

  <div class="stepwrap rwidth">
    <div class="stepnumber">
    </div>
    <div class="stepcontent">
      <% if current_organization.show_sub_orgs? && current_organization.has_children? %>
        <label for="survey_label">
          <%= raw(t('.association', this_term: current_organization.terminology, child_term: current_organization.children.first.terminology)) %>
          <div class="icon help tip help_bubble_keyword " title="<%= t('surveys.index_admin.association_help') %>"></div>
        </label>
        <div class="field">
          <%= f.select :organization_id, ([current_organization] + current_organization.children).collect {|o| [o.to_s, o.id]} %>
        </div>
      <% else %>
        <div class="field">
          <label for="survey_label">
            <strong><%= t('.survey_associated_with', org: current_organization) %></strong>
          </label>
        </div>
      <% end %>
    </div>
  </div>

	<div id="show_advanced_survey_option">Show Advanced Options</div>

	<div id="advanced_survey_option" class="hidden">
		<div class="stepwrap rwidth">
		  <div class="stepnumber">
		  </div>
		  <div class="stepcontent">
		    <div>
		      <strong><%= t('.customize_look') %></strong>
		      <br /><br />
		    </div>
		    <%= f.label :logo, t('.logo') %>
		    <div class="field">
		      <%= f.file_field :logo %>
		    </div>

		    <%= f.label :background_color, t('.background_color') %>
		    <div class="field">
		      <%= f.text_field :background_color %>
		    </div>

		    <%= f.label :text_color, t('.text_color') %>
		    <div class="field">
		      <%= f.text_field :text_color %>
		    </div>


		    <%= f.label :css_file, t('.css_file') %>
		    <div class="field">
		      <%= f.file_field :css_file %>
		    </div>

		    <%= f.label :css, t('.css') %>
		    <div class="field">
		      <%= f.text_area :css %>
		    </div>

		  </div>
		</div>

		<div class="stepwrap rwidth">
		  <div class="stepnumber">
		  </div>
		  <div class="stepcontent">
		    <label for="survey_label">
		      <%= t('.redirect_url') %>
		    </label>
		    <div class="field">
		      <%= f.text_field :redirect_url %>
		    </div>

		  </div>
		</div>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_other_orgs.html.erb
<% managed_orgs.each do |org| %>
  <div class="other_org" data-org-id="<%= org.id %>" data-org-name="<%= org.name %>">
    <%= org.name %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<tr>
  <td><%= survey %></td>
  <% if current_organization.show_sub_orgs? %>
    <td><%= survey.organization %></td>
  <% end %>
  <td><%= link_to(survey.keyword, edit_sms_keyword_path(survey.keyword)) if survey.keyword %></td>
  <td>
    <%= link_to(short_survey_url(survey.id, host: APP_CONFIG['public_host'], port: (APP_CONFIG['public_port'] == 80 ? nil : APP_CONFIG['public_port'])), short_survey_url(survey.id, host: APP_CONFIG['public_host'], port: (APP_CONFIG['public_port'] == 80 ? nil : APP_CONFIG['public_port'])), target: '_blank')%>
  </td>
  <td class="controls" align="right">
    <%= link_to t("welcome.home.manage_questions"), survey_questions_path(survey) %>
    <%= link_to t('surveys.index_admin.copy_survey'), "#transfer", class: "icon copy tipitleft transfer_survey", :title => t('surveys.index_admin.copy_survey'), "data-id" => survey.id, "data-name" => survey %>
    <%= link_to t('surveys.index_admin.edit_survey'), edit_survey_path(survey), class: "icon edit tipitleft", :title => t('surveys.index_admin.edit_survey') %>
    <%= link_to t("surveys.index_admin.delete_survey"), survey_path(survey), method: :delete, confirm: t('surveys.index_admin.confirm_delete_survey'), class: "icon delete tipitleft", title: t('surveys.index_admin.delete_survey') %>
  </td>
</tr>

app/views/surveys/_surveys_sidebar.html.erb
<% provide :sidebar do %>
  <div id="ac_sidebar">
    <div id="upper_sidebar_lists">
    <% if @survey.present? %>
      <%= link_to raw("<button class='red_accent full_width_button'>#{t('nav.all_surveys')}  (#{current_organization.surveys.count})</button>"), index_admin_surveys_path %>
      <% unless @survey.new_record? %>
         <!-- Buttons for Edit Survey page -->
        <%= link_to raw("<button class='action_gray full_width_button'>#{t('surveys.index_admin.preview_survey')}</button>"),
          new_survey_response_url(survey_id: @survey.id, host: APP_CONFIG['public_host'], port: APP_CONFIG['public_port']),
          target: "_blank" %>
        <%= link_to raw("<button class='action_gray full_width_button'>#{t('surveys.index_admin.delete_survey')}</button>"),
          survey_path(@survey), method: :delete, confirm: t('surveys.index_admin.confirm_delete_survey') %>
      <% else %>
         <!-- Buttons for New Survey page -->
         <%= link_to raw("<button class='action_gray full_width_button'>#{t('sms_keywords.index.request_keyword')}</button>"),
            new_sms_keyword_path %>
      <% end %>
    <% else %>
       <!-- Buttons For Surveys List-->
      <%= link_to raw("<button class='red_accent full_width_button'>#{t('nav.create_a_survey')}</button>"), new_survey_path %>
      <%= link_to raw("<button class='action_gray full_width_button'>#{t('sms_keywords.index.request_keyword')}</button>"),
          new_sms_keyword_path %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/surveys/_transfer_survey.html.erb
<div id="transfer_survey_div" style="display:none;" class="custom_mh_popup_box">
  <div class="ui-widget-overlay pop_box_overlay_container">&nbsp;</div>
  <div class="pop_box_container">
    <div class="mh_popup_box">
    	<div class="mh_popup_box_top">
        <span class="mh_popup_heading">
          <%= t("surveys.index_admin.copy_survey") %>
        </span>
      </div>
      <div class="mh_popup_box_content">
        <div class="fancy" id="transfer_survey_guide">
          You are about to copy the survey "<span id="survey_name"></span>" to another organization. Please select an organization you wish to have the same survey.
        </div>
        <div class="mh_popup_box_scroller">
          <div id="transfer_survey_processing">
            <%= image_tag 'loader.gif'%><br/>Copying Survey to <span id="org_name"></span><br/>Please wait...
          </div>
          <div id="transfer_survey_content">
            <div id="other_orgs_filter">
              <%= text_field_tag "filter", "keyword", id: "other_orgs_filter_keyword", value: "", placeholder: "Type to search organization", class: "ui-autocomplete-input" %>
            </div>
            <div id="other_orgs_list">
            </div>
          </div>
          <div id="transfer_survey_error">
          </div>
        </div>
      </div>
    	<div class="mh_popup_buttons">
    		<button class="large_lightgray mh_popup_cancel_button" id="">Cancel</button>
    	</div>
    </div>
  </div>
</div>

app/views/surveys/copy_survey.js.erb
<% if @status == 'copied' %>
  $.hideDialog($('#transfer_survey_div'))
<% else %>
  <% if @status == 'duplicate' %>
    msg = "<b><%= @receiving_org.name %></b> already have this survey."
  <% else %>
    msg = "Failed to copy the survey."
  <% end %>
  $('#transfer_survey_div #transfer_survey_error').html(msg)
  $('#transfer_survey_div #transfer_survey_error').show()
  $('#transfer_survey_div #transfer_survey_content').show()
  $('#transfer_survey_div #transfer_survey_processing').hide()
<% end %>

app/views/surveys/index.html.erb
<% if mhub? %>
  <% provide :title, t('.pick_keyword') %>
  <h1>Click on a keyword to complete a survey</h1>
  <ul>
    <% @surveys.each do |survey| %>
      <li>
        <%= link_to(survey, start_survey_url(survey.id, host: APP_CONFIG['public_host'], port: APP_CONFIG['public_port'])) %>
      </li>
    <% end %>
  </ul>
<% else %>

  <% provide :sidebar do %>
    <%= render 'surveys/left_sidebar' %>
  <% end %>

  <% if can? :manage, QuestionSheet %>
    <div class="titlebar">
      <h1><%= image_tag("c_survey.png") %><%= t('nav.surveys') %></h1>
    </div>
    <div class="pagemenu">
      <ul class="pillmenu">
        <li>
          <%= link_to(t(".new"), new_survey_path) %>
        </li>
      </ul>
    </div>
  
  
  
    <table class="listing keywordtable" cellpadding="0" cellspacing="0">
      <tr>
        <th class="check"></th>
        <th><%= t("general.survey") %></th>
        <% if current_organization.show_sub_orgs? %>
          <th><%= t("keywords.index.association") %> <%= tip(t('.association_help')) %></th>
        <% end %>
        <th><%= t("general.keyword") %></th>
        <th class="controls">&nbsp;</th>
      </tr>
      <% @surveys.each do |survey| %>
        <tr>
          <td class="checkbox"></td>
          <td><%= survey %></td>
          <% if current_organization.show_sub_orgs? %>
            <td><%= survey.organization %></td>
          <% end %>
          <td><%= survey.keyword if survey.keyword %></td>
          <td class="controls">
            <%= link_to t("welcome.home.manage_questions"), survey_questions_path(survey) %>
            <%= link_to('', edit_survey_path(survey), :class => "icon edit tipit", :title => t('.edit_survey')) %>
            <%= link_to t("welcome.home.delete"), survey_path(survey), method: :delete, confirm: t('.confirm_delete'), :class => "icon delete tipit", :title => t('.delete_survey') %>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="contentpad">
    
    </div>
  <% end %>
<% end %>