config/routes.rb
Mh::Application.routes.draw do

  resources :movement_indicators, only: [:index, :create] do
    collection do
      get :details
      get :error
    end
  end

  resources :movement_indicator_suggestions do
    collection do
      get :fetch_suggestions
      get :fetch_declined_suggestions
      get :confirm
      post :post_to_infobase
    end
  end


  get "dashboard/index"

  resources :imports, :only => [:show, :new, :create, :update, :destroy, :edit] do
    collection do
      get :download_sample_contacts_csv
      post :create_survey_question
      post :import
    end
  end

  # Interactions
  match 'profile/:id' => 'interactions#show_profile', as: "profile"
  resources :interactions do
    collection do
      get :change_followup_status
      get :reset_edit_form
      get :show_edit_interaction_form
      get :show_new_interaction_form
      get :search_initiators
      get :search_receivers
      get :load_more_interactions
      get :load_more_all_feeds
      get :create_label
      get :set_labels
      get :set_permissions
      get :set_groups
      get :search_leaders
    end
  end

  match 'imports/:id/labels' => 'imports#labels'
  match 'show_assign_search' => 'contacts#show_assign_search'
  match 'show_hidden_questions' => 'contacts#show_hidden_questions'
  match 'show_search_hidden_questions' => 'contacts#show_search_hidden_questions'
  match 'display_sidebar' => 'contacts#display_sidebar'
  match 'display_new_sidebar' => 'contacts#display_new_sidebar'
  match 'show_other_orgs' => 'surveys#show_other_orgs'
  match 'copy_survey' => 'surveys#copy_survey'
  match 'sent_messages' => 'messages#sent_messages'
  match 'search_locate_contact' => 'contacts#search_locate_contact'

  resources :group_labels, :only => [:create, :destroy]

  ActiveAdmin.routes(self)
  ActiveAdmin::ResourceController.class_eval do
    def authenticate_admin!
      unless user_signed_in? && SuperAdmin.find_by_user_id_and_site(current_user.id, 'MissionHub')
        render :file => Rails.root.join(mhub? ? 'public/404_mhub.html' : 'public/404.html'), :layout => false, :status => 404
        false
      end
    end
  end

  resources :groups do
    resources :group_labelings, :only => [:create, :destroy]
    resources :group_memberships, :only => [:create, :destroy] do
      collection do
        get :search
      end
    end
  end

  resources :survey_responses do
    collection do
      get :thanks
      get :facebook
      get :live
    end
  end

  resources :leaders, :only => [:new, :create, :update, :destroy] do
    collection do
      get :search
      put :add_person
    end
  end

  resources :organizational_permissions, :only => :update do
    collection do
      post :move_to
      post :update_all
    end
    member do
      get :set_current
      get :set_primary
    end
  end

  resources :organizational_labels do
    collection do
      post :update_all
    end
  end

  # resources :rejoicables

  resources :saved_contact_searches#, :only => [:show, :create, :edit, :destroy, :index]
  match "/saved_contact_searches/:id" => "saved_contact_searches#update"

  resources :followup_comments, :only => [:index, :create, :destroy]

  resources :contact_assignments, :only => [:create]

  resources :ministries

  resources :sms_keywords, :only => [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      post :accept_twilio
    end
  end

  match "/people" => "contacts#all_contacts"
  match "/allcontacts?assigned_to=unassigned" => "contacts#all_contacts", as: "unassigned_contacts"
  get "/contacts" => redirect("/allcontacts")
  match "/old_directory" => "people#index"
  resources :people, :only => [:show, :create, :edit, :update, :destroy] do
    collection do
      get :export
      get :merge
      post :confirm_merge
      post :do_merge
      get :hide_update_notice
      get :search_ids
      post :bulk_email
      post :bulk_sms
      post :bulk_comment
      get :all
      post :update_permissions
      post :update_permission_status
      post :bulk_delete
      post :bulk_archive
      get :facebook_search
      get :index
    end
    member do
      get :merge_preview
      get :involvement
    end
  end

  resources :labels, :only => [:create, :update, :destroy, :index, :new, :edit] do
    collection do
      post :create_now
      post :add_label
      post :edit_label
    end
  end

  namespace :admin do
    resources :email_templates

  end

  # namespace :admin do
  #   resources :organizations
  # end

  resources :organizations, :only => [:show, :new, :create, :edit, :update, :destroy, :index] do
    collection do
      get :search
      get :thanks
      post :signup
      get :settings
      post :update_settings
      get :cleanup
      get :transfer
      get :available_for_transfer
      get :queue_transfer
      post :do_transfer
      post :archive_contacts
      post :archive_leaders
      post :create_from_crs
      get :api
      get :generate_api_secret
      get :show_hidden_questions
      get :display_sidebar
    end
    member do
      get :update_from_crs
    end
  end

  resources :charts do
    collection do
      get :snapshot
      post :update_snapshot_movements
      post :update_snapshot_range
      get :goal
      get :trend
    end
  end

  resources :surveys, :only => [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get :start
    end
    collection do
      get :index_admin
      get :stop
    end
    resources :questions, controller: "surveys/questions" do
      member do
        put :hide
        put :unhide
      end
      collection do
        post :reorder
      end
    end
  end

  match "/dashboard" => "dashboard#index"
  get "welcome/index"
  get "welcome/duplicate"
  match 'tutorials' => "welcome#tutorials"
  get "/test" => "welcome#test"

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    match "/sign_in", to: "sessions#new"
    match "/sign_out", to: "sessions#destroy"
    match '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'
    match '/users/auth/facebook_mhub/callback', to: 'users/omniauth_callbacks#facebook_mhub'
  end
  match '/auth/facebook/logout' => 'application#facebook_logout', as: :facebook_logout

  match "/application.manifest" => OFFLINE

  post "sms/mo"
  get "sms/mo"

  match "/allcontacts" => "contacts#all_contacts", as: "all_contacts"
  match "/mycontacts" => "contacts#my_contacts", as: "my_contacts"
  match "/my_contacts_all" => "contacts#my_contacts_all", as: "my_contacts_all"
  resources :contacts, :only => [:show, :create, :edit, :update, :destroy, :index] do
    collection do
      get :all_contacts
      get :my_contacts
      get :mine
      get :mine_all
      get :contacts_all
      post :send_reminder
      put :create_from_survey
      delete :destroy
      post :bulk_destroy
      post :send_vcard
      get :send_bulk_vcard
      get :import_contacts
      post :csv_import
      get :download_sample_contacts_csv
      get :search_by_name_and_email
      get :auto_suggest_send_email
      get :auto_suggest_send_text
    end
  end

  resources :vcards, :only => [:create] do
    collection do
      get :bulk_create
    end
  end

  namespace :api do
    scope '(/:version)', version: /v\d+?/ do  #module: :api
      resources :people do
        collection do
          get :leaders
        end
      end
      resources :friends
      get 'contacts/search' => 'contacts#search'
      resources :contacts do
        resource :photo
      end
      get "contact_assignments/list_leaders" => "contact_assignments#list_leaders"
      get "contact_assignments/list_organizations" => "contact_assignments#list_organizations"
      resources :contact_assignments
      resources :followup_comments
      resources :interactions
      resources :roles
      resources :permissions
      resources :organizational_labels
      resources :organizational_permissions
      resources :organizations
    end
  end

  namespace :apis do

    api_version(module: 'V3', header: {name: 'API-VERSION', value: 'v3'}, parameter: {name: "version", value: 'v3'}, path: {value: 'v3'}) do
      resources :contact_assignments do
        collection do
          put :bulk_update
          delete :bulk_destroy
        end
      end
      resources :people do
        collection do
          get :ids
          delete :bulk_destroy
        end
      end
      resources :organizations
      resources :answers
      resources :surveys do
        resources :questions
      end
      resources :questions
      resources :followup_comments
      resources :roles
      resources :organizational_roles
      resources :interactions
      resources :interaction_types
      resources :labels
      resources :permissions
      resources :organizational_labels do
        collection do
          post :bulk
          post :bulk_create
          delete :bulk_destroy
        end
      end
      resources :organizational_permissions do
        collection do
          post :bulk
          post :bulk_create
          post :bulk_archive
          delete :bulk_destroy
        end
      end
    end
  end

  root to: "welcome#index"
#  match 'home' => 'welcome#home', as: 'user_root' ---- LOOK FOR THIS IN application_controller.rb
  match 'wizard' => 'welcome#wizard', as: 'wizard'
  match 'terms' => 'welcome#terms', as: 'terms'
  match 'privacy' => 'welcome#privacy', as: 'privacy'

  # SMS keyword state transitions
  match '/admin/sms_keywords/:id/t/:transition' => 'admin/sms_keywords#transition', as: 'sms_keyword_transition'
  match '/admin/sms_keywords/approve'

  match '/admin/organizations/:id/t/:transition' => 'admin/organizations#transition', as: 'organization_transition'
  match '/admin/organizations/approve'

  # Map keyword responses with phone numbers
  match 'c/:keyword(/:received_sms_id)' => 'survey_responses#new', as: 'contact_form'
  match 'm/:received_sms_id' => 'survey_responses#new'

app/controllers/api3/v3/surveys_controller.rb
class Api3::V3::SurveysController < Api3::V3::BaseController
  before_filter :get_survey, only: [:show, :update, :destroy]

  def index
    order = params[:order] || 'title'

    list = add_includes_and_filters(surveys, order: order)

    render json: list,
           callback: params[:callback],
           scope: includes
  end

  def show
    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  def create
    survey = surveys.new(params[:survey])

    if survey.save
      render json: survey,
             status: :created,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :bad_request,
             callback: params[:callback]
    end
  end

  def update
    if @survey.update_attributes(params[:survey])
      render json: @survey,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :bad_request,
             callback: params[:callback]
    end

  end

  def destroy
    @survey.destroy

    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  private

  def surveys
    current_organization.surveys
  end

  def get_survey
    @survey = add_includes_and_filters(surveys)
                .find(params[:id])

  end

  def available_includes
    [:keyword, :questions]
  end

end

app/controllers/apis/v3/questions_controller.rb
class Apis::V3::QuestionsController < Apis::V3::BaseController
  before_filter :get_question, only: [:show, :update, :destroy]

  def index
    order = params[:order] || 'survey_elements.position'

    list = add_includes_and_order(questions, order: order)

    render json: list,
           callback: params[:callback],
           scope: {include: includes, organization: current_organization, since: params[:since]}
  end

  def show
    render json: @question,
           callback: params[:callback],
           scope: {include: includes, organization: current_organization}
  end

  def create
    if survey
      question = params[:question].delete(:kind).constantize.new(params[:question])

      if question.save
        survey.elements << question
        survey.save

        render json: question,
               status: :created,
               callback: params[:callback],
               scope: {include: includes, organization: current_organization}
      else
        render json: {errors: question.errors.full_messages},
               status: :unprocessable_entity,
               callback: params[:callback]
      end
    else
      render json: {errors: "Your api key does not have access to the survey id you send in"},
             status: :unauthorized,
             callback: params[:callback]
    end

  end

  def update
    if @question.update_attributes(params[:question])
      render json: @question,
             callback: params[:callback],
             scope: {include: includes, organization: current_organization}
    else
      render json: {errors: question.errors.full_messages},
             status: :unprocessable_entity,
             callback: params[:callback]
    end
  end

  def destroy
    @question.destroy

    render json: @question,
           callback: params[:callback],
           scope: {include: includes, organization: current_organization}
  end

  private

  def questions
    survey.questions
  end

  def survey
    survey_id = params[:survey_id]
    survey_id ||= params[:question].delete(:survey_id) if params[:question]
    @survey ||= current_organization.surveys.find(survey_id)
  end

  def get_question
    @question = add_includes_and_order(questions)
                .find(params[:id])

  end

end

app/controllers/apis/v3/surveys_controller.rb
class Apis::V3::SurveysController < Apis::V3::BaseController
  before_filter :get_survey, only: [:show, :update, :destroy]

  def index
    order = params[:order] || 'title'

    list = add_includes_and_order(surveys, order: order)

    render json: list,
           callback: params[:callback],
           scope: {include: includes, since: params[:since]}
  end

  def show
    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  def create
    survey = surveys.new(params[:survey])

    if survey.save
      render json: survey,
             status: :created,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :unprocessable_entity,
             callback: params[:callback]
    end
  end

  def update
    if @survey.update_attributes(params[:survey])
      render json: @survey,
             callback: params[:callback],
             scope: includes
    else
      render json: {errors: survey.errors.full_messages},
             status: :unprocessable_entity,
             callback: params[:callback]
    end

  end

  def destroy
    @survey.destroy

    render json: @survey,
           callback: params[:callback],
           scope: includes
  end

  private

  def surveys
    current_organization.surveys
  end

  def get_survey
    @survey = add_includes_and_order(surveys)
                .find(params[:id])

  end

  def available_includes
    [:keyword, :questions]
  end

end

app/views/surveys/questions/_advanced_options.html.erb
<%= link_to t('surveys.questions.form.show_notification_options'), '#', id: 'advanced_toggle' %>
<br/>
<br/>
<div class="notify_advanced_options advanced_options hidden">
  <% notify_leaders = @auto_notify.present? ? @auto_notify.extra_parameters['leaders'] : [] %>
  <% notify_triggers = @auto_notify.present? ? @auto_notify.trigger_keywords : '' %>
  
  <% assign_contact_to_type = @auto_assign.present? ? @auto_assign.extra_parameters['type'] : 'Leader' %>
  <% assignment_trigger_words = @auto_assign.present? ? @auto_assign.trigger_keywords : '' %>
  <% autoassign_selected_id = @auto_assign.present? ? @auto_assign.extra_parameters['id'] : '' %>
  
  <div class="rule_form" id="AUTONOTIFY">
    <div class="title">▶ Automatic Notification for Leaders</div>
    <div class="settings">
      <div class="label">
        <%= t('.autonotify_guide') %>
      </div>    
      <br/>
      <div class="label">
        <label><%= t('.autonotify_leader_label') %></label>
      </div>    
      <div class="fieldset">
        <%= select_tag 'leaders[]',
          options_for_select(@leaders.collect {|l| [l.name, l.id] }, :selected => notify_leaders),
          {:multiple => true, :size => 7 } %>
      </div>
      <div class="label">
        <%= f.label :trigger_words, raw(t('.autonotify_keywords_label')) %>
      </div>
      <div class="fieldset">
        <%= text_field_tag :trigger_words, notify_triggers %>
      </div>
    </div>
  </div>
  
  <div class="rule_form" id="AUTOASSIGN">
    <div class="title">▶ Automatic Assignment of Contacts</div>
    <div class="settings">
      <div class="label">
        <%= t('.autoassign_guide') %>
      </div>    
      <br/>
      <div class="label">
        <label><%= t('.autoassign_group_label') %></label>
      </div>    
      <div class="fieldset">
        <%= radio_button_tag :assign_contact_to, '', false, id: 'assign_to_leader', class: 'assign_to_radio',
          value: "Leader", checked: assign_contact_to_type == "Leader" ? true : false %> 
        <label for="assign_to_leader"><%= t('leader') %></label>
        <%= radio_button_tag :assign_contact_to, '', false, id: 'assign_to_ministry', class: 'assign_to_radio',
          value: "Ministry", checked: assign_contact_to_type == "Ministry" ? true : false %> 
        <label for="assign_to_org"><%= current_organization.terminology %></label>
        <%= radio_button_tag :assign_contact_to, '', false, id: 'assign_to_group', class: 'assign_to_radio',
          value: "Group", checked: assign_contact_to_type == "Group" ? true : false %>
        <label for="assign_to_group"><%= t('group') %></label>
        <%= radio_button_tag :assign_contact_to, '', false, id: 'assign_to_label', class: 'assign_to_radio',
          value: "Label", checked: assign_contact_to_type == "Label" ? true : false %>
        <label for="assign_to_label"><%= t('label') %></label> 
      </div>
      
      <div id="autoassign_suggestion" class="autoassign_window">
        <div class="label">
          <%= f.label :autoassign_keyword, "Search #{assign_contact_to_type}:" %>
        </div>
        <div class="fieldset">
	        <%= text_field_tag :autoassign_keyword, '', id: 'autoassign_autosuggest', 'data-survey-id'=>s.id %>
          <%= hidden_field_tag :autoassign_selected_id, autoassign_selected_id, id: 'autoassign_selected_id' %>
        </div>
      </div>
      
      <div class="label">
        <%= f.label :assignment_trigger_words, raw(t('.autoassign_keywords_label')) %>
      </div>
      <div class="fieldset">
        <%= text_field_tag :assignment_trigger_words, assignment_trigger_words %>
      </div>
    </div>
  </div>
  
  <div class="rule_form" id="AUTONOTIFY">
    <div class="title">▶ Other Options</div>
    <div class="settings">
      <div class="label">
        <%= f.label :notify_via, t('.notify_via') %>
      </div>    
      <div class="fieldset">
        <%= f.select :notify_via, ["SMS","Email","Both"] %>
      </div>
      <div class="label">
       <%= f.check_box :web_only, id: "web_only_#{f.object.id}", class: 'web_only' %> <%= t('.web_only') %><br /><br/>
      </div>
      <div class="label">
       <%= f.check_box :hidden, id: "hidden_#{f.object.id}", class: 'web_only' %> <%= t('.hidden') %><br /><br/>
      </div>
    </div>
  </div>
</div>

app/views/surveys/questions/_display_rule.html.erb
<div class="title"><%= rule.name %></div>
<% case rule.rule_code %>
<% when 'AUTONOTIFY' %>

<% when 'AUTONOTIFY' %>
  
<% end %>

app/views/surveys/questions/_form.html.erb
<div class="inlineform" data-elem-id="<%= question.id %>">
  <%= form_for question, url: question.new_record? ? survey_questions_path(@survey) : survey_question_path(@survey, question),
                         method: question.new_record? ? :post : :put, remote: true, html: {class: 'question_form', id: question.new_record? ? 'new_question_form' : "form_for_#{question.id}"} do |f| %>
    <% if question.new_record? %>
    <div class="field">
      <label><%= t('.what_question_type') %></label>
      <%= select_tag('question_type', options_for_select([[t('.short_answer'), 'TextField:short'], [t('.multiple_choice'), 'ChoiceField:radio'], [t('.checkboxes'), 'ChoiceField:checkbox'], [t('.dropdown'),'ChoiceField:drop-down']]), include_blank: true, class: 'question_type') %>
    </div>
    <% end %>
    <div class="right_col" style="<%= 'display:none' if question.new_record? || question.web_only %>">
      <div class="sms_length_div">
        <label><%= t('.text_message_length') %></label>
        <span class="sms_length"><%= (question.kind == 'ChoiceField' ? question.label_with_choices : question.label).to_s.length %></span> / 140
      </div><br>
      <div class="sms_preview_div">
        <label><%= t('.text_message_preview') %></label><br/>
        <span class="sms_preview"><%= question.kind == 'ChoiceField' ? question.label_with_choices : question.label %></span>
      </div>
    </div>
    <div class="short_answer_form" style="<%= question.new_record? ? 'display:none' : '' %>">
      <%= render 'short_answer_form', f: f %>
    </div>
    <div class="multiple_choice_form" style="<%= (question.new_record? || question.kind == 'TextField') ? 'display:none' : '' %>">
      <%= render 'multiple_choice_form', f: f %>
    </div>
    <div class="submit_button" style="<%= question.new_record? ? 'display:none' : '' %>">
      <div id="advance_notification">
        <%= render 'advanced_options', f: f, q: question, s: @survey %>
      </div>
      <%= f.submit "Submit", :id => "save_edit_survey_question" %>
      <%= button_tag "Cancel", :id => "cancel_edit_survey_question" %>
    </div>
  <% end %>
</div>

app/views/surveys/questions/_multiple_choice_form.html.erb
<div class="field">
  <label><%= t('.list_choices') %></label>
  <%= f.text_area :content, rows: 5, id: "content_#{f.object.id}", class: 'content' %>
</div>

app/views/surveys/questions/_predefined_question.html.erb
<tr id="pre_<%= dom_id(question) %>">
  <td><%= question.label %></td>
  <td class="controls" align="right">
    <%= link_to('use', survey_questions_path(question_id: question),
      method: :post, remote: true, class: 'use_question icon add') %>
  </td>
</tr>

app/views/surveys/questions/_previous_used_questions.html.erb
<div id="previously_used" style="display:none;" class="custom_mh_popup_box">
  <div class="ui-widget-overlay pop_box_overlay_container">&nbsp;</div>
  <div class="pop_box_container">
    <div class="mh_popup_box">
    	<div class="mh_popup_box_top">
        <span class="mh_popup_heading" id="member_search_title">
          <%= t('surveys.questions.index.add_prev_question') %>
        </span>
      </div>
      <div class="mh_popup_box_content">
        <div class="mh_popup_box_scroller">
          <table class="listing contact_listing yourquestions" cellspacing="0" cellpadding="0">
            <tr id="table_header">
              <th>
                <%= t('surveys.questions.index.predefined') %> <%= tip(t('surveys.questions.index.predefined_help')) %>
              </th>
              <th>&nbsp;</th>
            </tr>
            <tbody id="predefined_questions">
              <% @predefined_questions.each do |question| %>
              	<% next if ['first_name','last_name','phone_number'].include?(question.attribute_name) %>
                <%= render 'predefined_question', question: question %>
              <% end %>
            </tbody>
          </table>

          <table class="listing contact_listing yourquestions" cellspacing="0" cellpadding="0">
            <tr id="table_header">
              <th>
                <%= t('surveys.questions.index.previously_used') %> <%#= tip(t('questions.previously_used_help')) %>
              </th>
              <th>&nbsp;</th>
            </tr>
            <tbody id="other_questions">
              <% @other_questions.each do |question| %>
                <%= render 'predefined_question', question: question %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    	<div class="mh_popup_buttons">
    		<button class="large_lightgray mh_popup_cancel_button" id="">Cancel</button>
    	</div>
    </div>
  </div>
</div>

app/views/surveys/questions/_question.html.erb
<tr id="question-<%= dom_id(question) %>">
  <td class="questiontitle"><%= question.label %></td>
  <td>
    <% if @predefined.questions.include?(question) %>
      <span class="icon_holder"></span>
    <% else %>
      <%= link_to('edit', edit_survey_question_path(@survey, question), remote: true, class: 'edit_question_show_loading edit_question icon edit tipitleft', title: t('surveys.questions.edit.edit_question')) unless @predefined.questions.include?(question) %>
    <% end %>
  </td>
  <td><%= link_to('remove', survey_question_path(@survey, question), method: :delete, confirm: t('.confirm_delete', question: question.label), remote: true, class: 'remove_question icon delete tipitleft', title: t('.delete_tip')) %></td>
</tr>

app/views/surveys/questions/add.js.erb
$('.inlineform').hide();
$('#new_question_form').closest('.inlineform').show();
$('#loading').hide();
$('#create_question_form').html('');
$('#create_question_form').html("<%= j(render('form', question: Question.new)) %>");
$('#create_question_form').slideDown();
$('.advanced_options').hide();
$('.sms_length').html(0);
$('.sms_preview').html('');
$.fn.tip()

$(document).ready(function() {
	autoassign_search();
});

app/views/surveys/questions/create.js.erb
<% unless params[:error] %>
  $('#questions').append("<%= j(render('question', question: @question)) %>")
  $('#saving').slideUp()
<% else %>
  $.a('<%=  params[:error] %>')
<% end %>

app/views/surveys/questions/destroy.js.erb
<% if @predefined.questions.include?(@question) %>
  $('#predefined_questions').append('<%= j(render('predefined_question', question: @question)) %>')
<% else %>
  $('#archived_questions').append('<%= j(render('predefined_question', question: @question)) %>')
<% end %>

app/views/surveys/questions/edit.js.erb
$('#create_question_form').html('');
$('#question_form').hide();
$('#question_form').html('<%= j(render('form', question: @question)) %>');
$('#loading').hide();
$('#question_form').slideDown();
$.fn.tip()

//Instantiate search if has data for Automatic Assignment of Contacts
$(document).ready(function() {
  <% name = @auto_assign.present? ? @auto_assign.extra_parameters['name'] : "" %>
  <% id = @auto_assign.present? ? @auto_assign.extra_parameters['id'] : "" %>
	autoassign_search("<%= id %>", "<%= name %>");
});

app/views/surveys/questions/index.html.erb
<%= render 'surveys/surveys_sidebar' %>

<div class="titlebar titlebarmod">
  <h1>
    <%= t('.manage', survey: @survey) %>
    <div id='global_loader'>
      <%= image_tag 'loader.gif'%>
    </div>
  </h1>
</div>

<div id="ac_button_bar">
	<ul class="button_bar">
		<li class="inlinehelp">
      <%= t('general.survey_web_tip_html', link: short_survey_url(@survey.id, host: APP_CONFIG['public_host'], port: (APP_CONFIG['public_port'] == 80 ? nil : APP_CONFIG['public_port']))) %>
		</li>
	</ul>
</div>
<br/>

<div id="ac_contact_spread">
  <p><%= t('.note') %></p>
  <h3><%= t('.your_questions') %> <spab class='icon help tip help_bubble_keyword' title="<%= t('.your_questions_help') %>">&nbsp;</span></h3>

  <table border="0" cellspacing="0" cellpadding="0" class="yourquestions fakesort">
    <tbody>
      <tr>
        <td class="questiontitle"><%= Element.find_by_attribute_name('first_name').present? ? Element.find_by_attribute_name('first_name').label : "First Name:" %></td>
        <td></td>
        <td><span class="icon lock tipitleft" title="<%= t('.forced_tip') %>"></span></td>
      </tr>
      <tr>
        <td class="questiontitle"><%= Element.find_by_attribute_name('last_name').present? ? Element.find_by_attribute_name('last_name').label : "Last Name:" %></td>
        <td><span class="icon_holder"></span></td>
        <td><span class="icon lock tipitleft" title="<%= t('.forced_tip') %>"></span></td>
      </tr>
      <tr>
        <td class="questiontitle"><%= Element.find_by_attribute_name('phone_number').label %></td>
        <td></td>
        <td><span class="icon lock tipitleft" title="<%= t('.forced_tip') %>"></span></td>
      </tr>
    </tbody>
  </table>
  <table border="0" cellspacing="0" cellpadding="0" class="yourquestions">
    <tbody id="questions" data-sortable="true" data-sortable-url="<%= reorder_survey_questions_path(@survey) %>">
      <%= render partial: 'question', collection: @questions %>
    </tbody>
  </table>

  <div class="button_block">
    <%= link_to(t('.add_question'), add_survey_question_path(@survey), {id:'add_suvey_question_link', remote: true, class: 'cleangray'}) %>
		<%= link_to(t('.add_prev_question'), '', id: 'add_old_question_link', class: "cleangray") %>
  </div>

  <div id='loading' class="hidden">
    <img src='/assets/loader.gif'>
    <br/>
    Loading Question
  </div>
  <div id='saving' class="hidden">
    <img src='/assets/loader.gif'>
    <br/>
    Saving Changes
  </div>
  <div id="create_question_form" class="hidden">
  </div>
  <div id="question_form" class="hidden">
  </div>
</div>

<!-- Previous Questions Dialog -->
<%= render 'surveys/questions/previous_used_questions' %>

app/views/surveys/questions/update.js.erb
$('#saving').slideUp()

app/views/surveys/questions/update_question_error.js.erb
$.a( "<%= t('surveys.questions.edit.leader_invalid_email_with_name', leader_names: leader_names) %>" )